// Generated by scripts/image-dimensions.mjs — do not edit by hand.
// Explicit width/height on every image prevents cumulative layout shift.

export type Dim = { w: number; h: number };

export const imageDimensions: Record<string, Dim> = {
  "/assets/badges/169358-967-2.png": {
    "w": 967,
    "h": 120
  },
  "/assets/badges/Urban-Customs-Google-Button.png": {
    "w": 850,
    "h": 175
  },
  "/assets/banners/cabinet-installation-slider.jpg": {
    "w": 2000,
    "h": 750
  },
  "/assets/banners/floor-refinishing-slider.jpg": {
    "w": 2000,
    "h": 750
  },
  "/assets/banners/floor-repair-slider.jpg": {
    "w": 2000,
    "h": 750
  },
  "/assets/banners/kitchen-remodeling-slider-02.jpg": {
    "w": 2000,
    "h": 750
  },
  "/assets/coupons/urban-customs-design-coupon-2026.jpg": {
    "w": 1200,
    "h": 600
  },
  "/assets/coupons/urban-customs-free-shipping-coupon-2026.jpg": {
    "w": 1200,
    "h": 600
  },
  "/assets/coupons/urban-customs-installation-coupon-2026.jpg": {
    "w": 1200,
    "h": 600
  },
  "/assets/gallery/pic001-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic002-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic003-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic004-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic005-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic006-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic007-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic008-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic009-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic010-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic011-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic012-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic013-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic014-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic015-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic016-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic017-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic018-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic019-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic020-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic021-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic022-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic023-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic024-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic025-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic026-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic027-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic028-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic030-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic031-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic032-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic033-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic035-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/gallery/pic036-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/icons/check-mark-icon.png": {
    "w": 250,
    "h": 250
  },
  "/assets/icons/design.png": {
    "w": 500,
    "h": 500
  },
  "/assets/icons/installation-icon.png": {
    "w": 500,
    "h": 500
  },
  "/assets/icons/warranty.png": {
    "w": 500,
    "h": 500
  },
  "/assets/images/Hardwood-Floor-Refinishing-Phoenix-AZ.jpg": {
    "w": 1172,
    "h": 288
  },
  "/assets/images/interior-stone-installations-in-arizona.jpg": {
    "w": 1200,
    "h": 1200
  },
  "/assets/images/phoenix-flooring-installations-after-image.jpg": {
    "w": 480,
    "h": 640
  },
  "/assets/images/phoenix-flooring-installations-before-image.jpg": {
    "w": 480,
    "h": 640
  },
  "/assets/images/phoenix-flooring-installations-during-image.jpg": {
    "w": 480,
    "h": 640
  },
  "/assets/images/pic007-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/images/pic035-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/images/pic036-with-logo.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/images/the-urban-customs-kitchen-remodeling-process.jpg": {
    "w": 1200,
    "h": 1200
  },
  "/assets/images/tile-floor-004.jpg": {
    "w": 2000,
    "h": 533
  },
  "/assets/images/tile-floor-005.jpg": {
    "w": 2000,
    "h": 389
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-001.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-002.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-003.jpg": {
    "w": 900,
    "h": 1200
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-004.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-005.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-006.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-007.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-008.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-009.jpg": {
    "w": 1200,
    "h": 900
  },
  "/assets/kitchen/arizona-kitchen-remodeling-by-urban-customs-img-010.jpg": {
    "w": 900,
    "h": 1200
  },
  "/assets/logos/urban-customs-new-logo-1200px.png": {
    "w": 1200,
    "h": 400
  },
  "/assets/logos/urban-customs-new-logo-600px.png": {
    "w": 600,
    "h": 200
  },
  "/assets/logos/urban-customs-square-logo-800px.png": {
    "w": 800,
    "h": 600
  },
  "/assets/logos/urban-customs-white-logo.png": {
    "w": 1200,
    "h": 400
  },
  "/assets/staging/bamboo-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 575
  },
  "/assets/staging/cabinet-installations-by-urban-customs.jpg": {
    "w": 750,
    "h": 575
  },
  "/assets/staging/custom-flooring-slider.jpg": {
    "w": 2000,
    "h": 1200
  },
  "/assets/staging/flooring-bg.jpg": {
    "w": 2000,
    "h": 1250
  },
  "/assets/staging/flooring-restoration-slider.jpg": {
    "w": 2000,
    "h": 1200
  },
  "/assets/staging/guest-bathroom-stone-tile-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/staging/hardwood-flooring-by-urban-customs-in-az.jpg": {
    "w": 750,
    "h": 575
  },
  "/assets/staging/kitchen-cabinet-slider.jpg": {
    "w": 2000,
    "h": 1200
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-001.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-002.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-003.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-004.jpg": {
    "w": 768,
    "h": 1024
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-005.jpg": {
    "w": 1024,
    "h": 683
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-006.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-007.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-008.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-009.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-010.jpg": {
    "w": 1024,
    "h": 768
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-011.jpg": {
    "w": 768,
    "h": 1024
  },
  "/assets/staging/kitchen-remodeling-by-urban-customs-az-img-012.jpg": {
    "w": 1000,
    "h": 1000
  },
  "/assets/staging/kitchen-remodeling-in-az.jpg": {
    "w": 900,
    "h": 600
  },
  "/assets/staging/kitchen-stone-tile-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/staging/laminate-flooring-services-in-phoenix-az.jpg": {
    "w": 1200,
    "h": 800
  },
  "/assets/staging/living-room-stone-tile-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/staging/master-bathroom-stone-tile-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/staging/outdoor-stone-tile-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/staging/professional-flooring-contractors-in-az.jpg": {
    "w": 1500,
    "h": 1000
  },
  "/assets/staging/shower-stone-tile-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 525
  },
  "/assets/staging/stone-floor-installation-services-in-arizona.jpg": {
    "w": 1200,
    "h": 800
  },
  "/assets/staging/stone-flooring-by-urban-customs.jpg": {
    "w": 750,
    "h": 575
  },
  "/assets/staging/stone-flooring-installations-in-arizona.jpg": {
    "w": 1200,
    "h": 1200
  },
  "/assets/staging/urban-customs-favicon-300x300.png": {
    "w": 300,
    "h": 300
  },
  "/assets/staging/urban-customs-favicon.png": {
    "w": 500,
    "h": 500
  },
  "/assets/staging/urban-customs-floor-designs-and-installations-img-01.jpg": {
    "w": 1000,
    "h": 1000
  },
  "/assets/staging/urban-customs-floor-designs-and-installations-img-02.jpg": {
    "w": 1000,
    "h": 1000
  },
  "/assets/staging/urban-customs-floor-designs-and-installations-img-03.jpg": {
    "w": 1000,
    "h": 1000
  },
  "/assets/staging/urban-customs-floor-designs-and-installations-img-04.jpg": {
    "w": 1000,
    "h": 1000
  },
  "/assets/staging/urban-customs-white-logo-300px.png": {
    "w": 300,
    "h": 100
  },
  "/assets/staging/urban-customs-white-logo-600px.png": {
    "w": 600,
    "h": 200
  }
};

export function dim(src: string): Dim {
  return imageDimensions[src] ?? { w: 1200, h: 800 };
}
